project:
  type: website

website:
  title: "Your Blog Name"
  description: "Thinking clearly about X"
  site-url: https://YOUR_USERNAME.github.io/lw-blog
  navbar:
    left:
      - text: Posts
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    html-math-method: katex
    link-external-newwindow: true
