project:
  type: website

website:
  title: "Test name"
  description: "Some description"
  site-url: https://dec0dedd.github.io
  navbar:
    left:
      - text: Posts
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    html-math-method: katex
    link-external-newwindow: true
